### ISSUE TITLE
Invalid stub

### ISSUE THREAD

**Issue by orangejuice8078** [susMdT/SharpIndirectSyscalls#1]
Hello. I was testing this code, and when I build it and open it, it shows me "Invalid stub, gonna assume the managed method address is the method table entry".
But the thing is that functions like NtProtectVirtualMemory NtAllocateVirtualMemory NtWriteVirtualMemory are working, and their status is 0. Why is this happening? I use windows 11 64-bit

**Comment by orangejuice8078** [comment]
![Screenshot (50)](https://github.com/susMdT/SharpIndirectSyscalls/assets/138825019/a36e0478-9dbd-4159-8c3a-c7fa79eb17db)
![Screenshot (51)](https://github.com/susMdT/SharpIndirectSyscalls/assets/138825019/e605c365-eec6-4831-8e8d-7dea1f98aa8c)

**Comment by susMdT** [comment]
Oh this was a debug message I wrote out a long time ago. There's a weird .NET internals thing with the method table if i recall correctly. I believe on .NET 5 the method table entry contains a jmp to the address of the jitted machine code, whereas .net framework it just has the code.

As to the reason why this is relevant, we are forcing the CLR to jit compile a method and using its jitted code to write our syscall stub. .NET jit does rwx memory so we just need to copy our stub in
```
        /// <summary>
        /// Jit the Gate
        /// 1. Follow JMP to find machine code of JITTED method and designate it for our syscall writing
        /// </summary>
        public void GenerateRWXMemorySegment()
        {
            // Find and JIT the method?
            MethodInfo method = typeof(dll).GetMethod(nameof(Gate), BindingFlags.Static | BindingFlags.Public);
            RuntimeHelpers.PrepareMethod(method.MethodHandle);
            // Get the address of the function to find JITted machine code or figure out if JIT went weird
            IntPtr pMethod = method.MethodHandle.GetFunctionPointer();
            if (Marshal.ReadByte(pMethod) != 0xe9)
            {
                Console.WriteLine("Invalid stub, gonna assume the managed method address is the method table entry");
                pCove = pMethod;
                return;
            }
            Int32 offset = Marshal.ReadInt32(pMethod, 1);
            UInt64 addr64 = 0;

            addr64 = (UInt64)pMethod + (UInt64)offset;
            while (addr64 % 16 != 0)
                addr64++;
            pCove = (IntPtr)addr64;
            return;
        }
```
